# Application Name
spring.application.name=grievance

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/grievance_db
spring.datasource.username=root
spring.datasource.password= simar12kalra@26

# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
